name: Integration Workflow

on:
  push:
    branches: [main]

jobs:
  build-tests:
    name: Build test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend-next/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: frontend-next

      - name: Run Build
        run: npm run build
        working-directory: frontend-next
        
  python-build:
    name: Python application
    runs-on: ubuntu-latest

    services:
      weaviate:
        image: semitechnologies/weaviate:latest
        ports:
          - 8080:8080
        env:
          QUERY_DEFAULTS_LIMIT: 25
          AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
          PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
          DEFAULT_VECTORIZER_MODULE: 'none'
          ENABLE_MODULES: ''
      
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pytest requests redis fastapi-limiter uvicorn
        
    - name: Check formatting with Black
      working-directory: ./backend
      run: |
        black --check .
      
    - name: Test Redis connection
      run: |
        python -c "
        import time
        import redis

        r = redis.Redis(host='localhost', port=6379)
        for i in range(7):
            try:
                if r.ping():
                    print('Redis is ready')
                    exit(0)
            except redis.exceptions.ConnectionError:
                print(f'Waiting for Redis... ({i+1})')
                time.sleep(2)
        print('Redis did not start in time')
        exit(1)
        "

    - name: Run application health check
      working-directory: ./backend
      run: |
        python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
        echo "Waiting for the server to start..."
        for i in {1..7}; do
          if curl -fs http://localhost:8000/health > /dev/null; then
            echo "Server is up!"
              exit 0
          fi
          echo "Still waiting ($i)..."
          sleep 2
        done
        echo "Server failed to start in time."
        exit 1